name: 'Upload a Build Artifact'
description: 'Upload a build artifact that can be used by subsequent workflow steps'
inputs:
  name:
    description:
    default: 'artifact'
  path:
    description:
    required: true
  if-no-files-found:
    description:
    default: 'warn'
  retention-days:
    description:
  compression-level:
    description:
    default: '6'
  overwrite:
    description:
    default: 'false'
  include-hidden-files:
    description:
    default: 'false'

outputs:
  artifact-id:
    description:
    value: ${{ steps.action.outputs.ref.artifact-id }}
  artifact-url:
    description:
    value: ${{ steps.action.outputs.ref.artifact-url }}
runs:
  using: "composite"
  steps:
  - name: Upload Artifact
    id: action
    continue-on-error: true
    uses: actions/upload-artifact@v4
    with:
      compression-level: ${{ inputs.compression-level }}
      if-no-files-found: ${{ inputs.if-no-files-found }}
      include-hidden-files: ${{ inputs.include-hidden-files }}
      name: ${{ inputs.name }}
      overwrite: ${{ inputs.overwrite }}
      path: ${{ inputs.path }}
      retention-days: ${{ inputs.retention-days }}
