#!/bin/sh
set -e

if git ls-files --stage|grep ^16000; then
  git_submodule_output=$(mktemp)
  if ! git submodule 2>"$git_submodule_output"; then
    rm -f .gitmodules
    q="'" perl -e '
      my $git_modules;
      my $now = time();
      while (<>) {
        next unless /^fatal: no submodule mapping found in .gitmodules for path $ENV{q}(.*)$ENV{q}.*/;
        open $git_modules, q">>", q".gitmodules" unless $git_modules;
        print $git_modules qq<[submodule "synthetic-module-$now-$."]\n	path = $1\n	url = https://localhost:1/\n>;
      }
    ' "$git_submodule_output";
  fi
  git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
  git checkout HEAD -- .gitmodules || true
fi
