#!/bin/bash
if [ "$1" = 'config' ] || [ "$1" = 'version' ]; then
  /tmp/.check-spelling-git-logs/git "$@" 2> /dev/null
  exit $?
fi

sha=$(echo "${repo_path:-$(pwd)}"|shasum|perl -pe 's/\s.*//')
git_logs=/tmp/.check-spelling-git-logs/${sha%* -}

mkdir -p "$git_logs"
out="${checkout_git_out:-$git_logs/out}"
err="${checkout_git_err:-$git_logs/err}"
(
  echo "err=$err"
  echo "out=$out"
) >> "$GITHUB_OUTPUT"
touch "$err"

set -o pipefail
(
  log="$(mktemp)"
  /tmp/.check-spelling-git-logs/git "$@" 2> "$log"
  result=$?
  if [ $result -ne 0 ]; then
    cat "$log" | tee -a "$err" >&2
  fi
  exit $result
) | tee -a "$out"
