#!/bin/sh
if [ "$INPUT_TASK" != 'hash-dictionaries' ]; then
  if ! command -v php > /dev/null; then
    echo "[$(date)] installing php..."
    apt-get update -q >/dev/null 2>/dev/null &&
    apt-get install -q -y php-cli >/dev/null 2>/dev/null &&
    echo "[$(date)] ... installed php"
  fi
  (cd $THIS_ACTION_PATH/t/with-dictionaries; /usr/bin/env php -S '[::]':8123 )&
  php_pid=$!
fi
stdbuf -i0 -o0 -e0 $THIS_ACTION_PATH/unknown-words.sh
result=$?
if [ -n "$php_pid" ]; then
  kill $php_pid
fi
exit $result
