#!/bin/sh
export CANARY_HOME=$(mktemp -d)
if [ "$INPUT_TASK" != 'hash-dictionaries' ]; then
  if ! command -v lsof >/dev/null 2>/dev/null; then
    APT_PACKAGES="lsof $APT_PACKAGES"
  fi
  if ! command -v php > /dev/null; then
    APT_PACKAGES="php-cli $APT_PACKAGES"
  fi
  if [ -n "$APT_PACKAGES" ]; then
    echo "[$(date)] installing $APT_PACKAGES..."
    apt-get update -q >/dev/null 2>/dev/null &&
    apt-get install -q -y $APT_PACKAGES >/dev/null 2>/dev/null &&
    echo "[$(date)] ... installed $APT_PACKAGES"
  fi
  old_server=$(
    lsof -iTCP -n -P |
    grep 8123 |
    perl -ne 'next unless s/^php\s+(\d+).*/$1/;print'
  )
  if [ -n "$old_server" ]; then
    kill -9 "$old_server"
  fi
  (cd $THIS_ACTION_PATH/t/with-dictionaries; /usr/bin/env php -S '[::]':8123 )&
  php_pid=$!
fi
stdbuf -i0 -o0 -e0 $THIS_ACTION_PATH/unknown-words.sh
result=$?
if [ -n "$php_pid" ]; then
  kill $php_pid
fi
exit $result
