name: Test
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:

jobs:
  perl:
    name: Perl
    permissions:
      contents: read
    runs-on: ubuntu-latest
    if: contains(github.event_name, 'pull_request') || github.event_name == 'push'
    steps:
    - name: Checkout merge
      if: contains(github.event_name, 'pull_request')
      uses: actions/checkout@v7
      with:
        ref: refs/pull/${{github.event.pull_request.number}}/merge
      env:
        GIT_CURL_VERBOSE: True
        GIT_TRACE: True
        GIT_SSH_COMMAND: ssh -v -v -v
    - name: Checkout
      if: github.event_name == 'push'
      uses: actions/checkout@v7
      env:
        GIT_CURL_VERBOSE: True
        GIT_TRACE: True
        GIT_SSH_COMMAND: ssh -v -v -v
    - name: Perl configuration
      id: perl-config
      run: |
        : Perl configuration
        perl_modules="$(
          echo "
          Module::Build::Tiny
          Devel::Cover
          Devel::Cover::Report::Html
          Capture::Tiny
          Hash::Merge
          Text::Hunspell
          YAML::PP
          " |sort|xargs)"
        (
          echo "perl-modules=$perl_modules"
        ) >> "$GITHUB_OUTPUT"
    - name: Dependencies
      id: dependencies
      shell: bash
      env:
        required_perl_modules: ${{ steps.perl-config.outputs.perl-modules }}
        GH_TOKEN: ${{ github.token }}
        GIT_CURL_VERBOSE: True
        GIT_TRACE: True
        GIT_SSH_COMMAND: ssh -v -v -v
      run: |
        : Dependencies
        (
          cpan_modules=$(
            for module in $required_perl_modules; do
              perl -e "use $module; 1;" > /dev/null 2>/dev/null || echo $module
            done | xargs
          )
          command -v tesseract >/dev/null 2>/dev/null || APT_PACKAGES="tesseract-ocr $APT_PACKAGES"
          command -v cover >/dev/null 2>/dev/null || APT_PACKAGES="libdevel-cover-perl $APT_PACKAGES"
          if command -v apt-get >/dev/null 2>/dev/null && ! command -v cpanm >/dev/null 2>/dev/null; then
            APT_PACKAGES="cpanminus $APT_PACKAGES"
          fi
          wants_cpan_modules() {
            [ -n "$cpan_modules$force_cpan_modules" ]
          }
          if [ -n "$APT_PACKAGES" ]; then
            if wants_cpan_modules; then
              APT_PACKAGES="$APT_PACKAGES $(
                for a in $cpan_modules $force_cpan_modules; do
                  apt-cache search lib$(echo $a|perl -pe 's/::/-/g')-perl;
                done|perl -pe 's/ -.*//'
              )"
            fi
            # Skip installing package docs to make the man-db trigger much faster
            (for exclude in doc man info; do echo "path-exclude /usr/share/$exclude/*"; done) |
              sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc > /dev/null
            if ! sudo apt-get install -y -q $APT_PACKAGES 2>/dev/null; then
              disable_apt_repository() {
                parent=/etc/apt/sources.list.d
                if [ -f "$parent/$1" ]; then
                  sudo mv "$parent/$1" "$parent/$1.disabled"
                fi
              }
              for repository in azure-cli.sources github_git-l"f"s.list micro"soft"-prod.list; do
                disable_apt_repository "$repository"
              done
              if [ -f /etc/apt/sources.list.d/ubuntu.sources ]; then
                sudo perl -pi.disabled -e '
                  if (/Components:/) { s/\b(?:restricted|multiverse)\b//g; };
                  if (/Suites:/) { s/\b\w+-(?:updates|backports)\b//g; };
                ' /etc/apt/sources.list.d/ubuntu.sources
              else
                sudo perl -pi.disabled -e '
                  s%^(deb https?://\S+\s+\w+-.*)%#$1%;
                  next if /^#/;
                  s%^(deb https?://\S+\s+\w+ multiverse)%#$1%;
                  s%\bmain restricted\b%main # restricted%;
                ' /etc/apt/sources.list
              fi

              sudo apt-get update &&
              sudo apt-get install -y -q $APT_PACKAGES
            fi
            if ! command -v gh >/dev/null; then
              apt_policy=$(mktemp)
              apt-cache policy gh > "$apt_policy"
              if grep -q 'Candidate: 2.4.0' "$apt_policy"; then
                extra_bin=~/bin
                mkdir -p "$extra_bin"
                echo "gh-location=$extra_bin/gh" >> "$GITHUB_OUTPUT"
                echo "$extra_bin" >> "$GITHUB_PATH"
              else
                sudo apt-get install gh
              fi
            fi
          fi
          if cover --version | perl -e '
            use version;
            my $v=<>;
            $v =~ s/.* version //;
            $v = 0 unless $v =~ /\d/;
            $v = "v$v" if $v =~ /^\d/;
            exit 0 if version->parse($v) < version->parse("v1.52");
            exit 1;
          '; then
            force_cpan_modules="Devel::Cover $force_cpan_modules"
          fi
          if wants_cpan_modules; then
            cpan_modules=$(
              for module in $required_perl_modules; do
                perl -e "use $module; 1;" > /dev/null 2>/dev/null || echo $module
              done | xargs
            )
            if wants_cpan_modules; then
              if ! command -v cpanm >/dev/null 2>/dev/null; then
                curl -s -S -L https://cpanmin.us | perl - --sudo App::cpanminus
              fi
              perl `command -v cpanm` -S --notest $cpan_modules $force_cpan_modules
            fi
          fi
        )

    - name: Install gh
      if: steps.dependencies.outputs.gh-location
      uses: ./actions/gh-program-downloader
      with:
        repository: cli/cli
        destination: ${{ steps.dependencies.outputs.gh-location }}
        file-re: bin/
        trace: 1
      env:
        GIT_CURL_VERBOSE: True
        GIT_TRACE: True
        GIT_SSH_COMMAND: ssh -v -v -v

    - name: Test
      id: test
      shell: bash
      env:
        required_perl_modules: ${{ steps.perl-config.outputs.perl-modules }}
        GH_TOKEN: ${{ github.token }}
      run: |
        : Test
        ./Build.PL
        ./Build build
        (
          cd lib;
          for m in $(
            find * -name '*.pm' |
              perl -pe 's!/!::!g;s/\.pm$//'
          ); do
            perl -I. -M$m -e ''
          done
        )
        cover_output=$(mktemp)
        perl `command -v cover` -test 2>&1 | tee -a "$cover_output" || failed=$?
        echo '::group::cover'
        (
          echo '# Tests'
          echo 'test|result';
          echo '-|-';
          perl -e '
            $new_state = 0;
            my $no_such_file = "Could not open file (no-such-file)";
            while (<>) {
            if (m<t/.*\.t \.+ \w*$|^---|^\s*Failed test:|^\s*Non-zero exit status:|\([W]stat>) {
              $new_state = 1;
            }
            next unless ($new_state || $state);
            last if /^--+(?: --+){3}/;
            $state = $new_state;
            next unless /\w/;
            next if $last_line eq $_;
            next if /\Q$no_such_file\E/;
            next if /^Files=\d+, Tests=\d+,/;
            next if /^(?:Reading database from |Devel::Cover: merging data)/;
            $last_line = $_;
            s/ \.+ ok/|✅/ || s/ \.+ /|/;
            s/^\s+(.*):\s*/... $1|/;
            s/^# (Looks like.*[^.])\.$/... $1|⚠️/;
            s/\s+(\([Ww]stat)/|❌ $1/ unless /\|/;
            s/All tests successful\./&nbsp;|\nAll tests|✅/;
            s/Result: PASS/Result|✅/;
            s/Result: FAIL/Result|❌/;
            s/\.($)/|😳$1/ if / at .* line \d+\./ && !/\|/;
            print;
            }' "$cover_output"
          echo
          echo '<details><summary>Details</summary>'
          echo
          echo '```'
          cat "$cover_output"
          echo '```'
          echo '</details>'
        ) >> "$GITHUB_STEP_SUMMARY"
        echo ::endgroup::
        for run in t/*/run; do
          output=$(dirname $run)
          diff -u $output/output $run || true
        done |
          perl -pe 's<^((?:diff -u|---|[+]{3}) t/[^/]+)/run(/\S+\s)><$1/output$2>;' > run.diff
        if [ -s run.diff ]; then
          echo "run-diff=1" >> "$GITHUB_OUTPUT"
        fi
        echo 'ran=1' >> "$GITHUB_OUTPUT"
        exit $failed
    - name: Calculate coverage
      id: coverage
      if: steps.test.outputs.ran == 1 && (success() || failure())
      run: |
        : Calculate coverage
        cover_command=`command -v cover`
        if [ -n "$cover_command" ]; then
        perl "$cover_command" -ignore /usr/bin/shasum -report html
        fi
        if [ -e cover_db/coverage.html ]; then
          (
            t/html-to-markdown.pl cover_db/coverage.html
          ) >> "$GITHUB_STEP_SUMMARY"
        fi
        echo 'ran=1' >> "$GITHUB_OUTPUT"
    - name: Publish coverage to pages
      if: (success() || failure()) && (steps.coverage.outputs.ran == 1) && env.has_coverage_repository
      uses: ./actions/publish-coverage
      with:
        repository: ${{ vars.coverage_repository }}
        ssh-key: ${{ secrets.coverage_repository_key }}
        pages-base-url: ${{ vars.github_pages_base }}
      env:
        has_coverage_repository: ${{ vars.coverage_repository && secrets.coverage_repository_key && 1 || '' }}
    - name: Store coverage
      if: (success() || failure()) && (steps.coverage.outputs.ran == 1)
      uses: ./actions/upload-artifact
      timeout-minutes: 5
      with:
        name: "check-spelling-coverage-${{ github.run_id }}"
        path: |
          cover_db
    - name: Store run output
      if: (success() || failure()) && (steps.test.outputs.run-diff == 1)
      uses: ./actions/upload-artifact
      timeout-minutes: 5
      with:
        name: "check-spelling-run-diff-${{ github.run_id }}"
        path: |
          run.diff

  standalone:
    name: Standalone
    permissions:
      contents: read
    runs-on: ubuntu-latest
    if: contains(github.event_name, 'pull_request') || github.event_name == 'push'
    steps:
    - name: Checkout merge
      if: contains(github.event_name, 'pull_request')
      uses: actions/checkout@v7
      with:
        ref: refs/pull/${{github.event.pull_request.number}}/merge
      env:
        GIT_CURL_VERBOSE: True
        GIT_TRACE: True
        GIT_SSH_COMMAND: ssh -v -v -v
    - name: Checkout
      if: github.event_name == 'push'
      uses: actions/checkout@v7
      env:
        GIT_CURL_VERBOSE: True
        GIT_TRACE: True
        GIT_SSH_COMMAND: ssh -v -v -v
    - name: Test
      id: test
      shell: bash
      run: |
        : Test
        git clone . ../introspected/
        mv ../introspected .
        cp .git/config introspected/.git
        step_summary="$GITHUB_STEP_SUMMARY"
        output="$GITHUB_OUTPUT"
        workflow_ref=$(echo "$GITHUB_WORKFLOW_REF" | perl -pe 's</[^/]+@></spelling.yml@>')
        for github_var in $(
          git ls-files -z |
          xargs -0 grep GITHUB_ |
          perl -pe 's/[^_A-Z]+/\n/g' |
          grep ^GITHUB_ |
          sort -u
        ); do
          eval unset $github_var
        done
        unset ACT
        export GITHUB_STEP_SUMMARY="$step_summary"
        export GITHUB_OUTPUT="$output"
        export GITHUB_WORKFLOW_REF="$workflow_ref"
        export GITHUB_REPOSITORY=check-spelling/check-spelling
        export APPLY_SKIP_UPDATE_CHECK=1
        ./unknown-words.sh || true
        grep -q '@check-spelling-bot Report' "$GITHUB_STEP_SUMMARY"
    - name: Upload artifact
      id: upload-artifact
      uses: ./actions/upload-artifact
      with:
        name: standalone-artifact
        path: |
          ${{ steps.test.outputs.internal_state_directory }}
    - name: Add artifact note to summary
      if: steps.upload-artifact.outcome == 'success'
      run: |
        : Artifact note
        cat <<EOF >> "$GITHUB_STEP_SUMMARY"
        ## apply.pl and artifact
        You should be able to use [\`apply.pl\`](https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$GITHUB_SHA/apply.pl) with \`standalone-artifact\`.
        EOF
